version: '3'

services:
  telegram-bot:
    build: ./telegram-bot
  mongo:
    image: mongo
  backend:
    build: ./backend
    ports:
      - 8001:8000
  frontend:
    build: ./frontend
    ports:
      - 3001:3000
